# Car Damage Detection – Dataset 3 (6 classes)

# Your dataset3 root folder
path: D:/IIT/4 th Year/Machine Vision/Course Work/Car-Damage-Detection-YOLO/data/dataset3

# Folders relative to "path"
train: train/images
val: valid/images
test: test/images

nc: 6
names:
  0: crack
  1: dent
  2: glass shatter
  3: lamp broken
  4: scratch
  5: tire flat